#ifndef OWL_HOOT_H
#define OWL_HOOT_H

#include <pgmspace.h>

// This array will be generated by xxd -i command
extern const unsigned char owl_sound_data[] PROGMEM;
extern const unsigned int owl_sound_size;

#endif